// Code generated by MockGen. DO NOT EDIT.
// Source: /opt/gophkeeper/internal/client/core/services/data_service/api/service.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	changes "github.com/besean163/gophkeeper/internal/client/core/services/data_service/api/changes"
	client "github.com/besean163/gophkeeper/internal/models/client"
	gomock "github.com/golang/mock/gomock"
)

// MockChangeDetector is a mock of ChangeDetector interface.
type MockChangeDetector struct {
	ctrl     *gomock.Controller
	recorder *MockChangeDetectorMockRecorder
}

// MockChangeDetectorMockRecorder is the mock recorder for MockChangeDetector.
type MockChangeDetectorMockRecorder struct {
	mock *MockChangeDetector
}

// NewMockChangeDetector creates a new mock instance.
func NewMockChangeDetector(ctrl *gomock.Controller) *MockChangeDetector {
	mock := &MockChangeDetector{ctrl: ctrl}
	mock.recorder = &MockChangeDetectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChangeDetector) EXPECT() *MockChangeDetectorMockRecorder {
	return m.recorder
}

// GetAccountChanges mocks base method.
func (m *MockChangeDetector) GetAccountChanges(user client.User, compare changes.AccountCompare) changes.AccountChanges {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountChanges", user, compare)
	ret0, _ := ret[0].(changes.AccountChanges)
	return ret0
}

// GetAccountChanges indicates an expected call of GetAccountChanges.
func (mr *MockChangeDetectorMockRecorder) GetAccountChanges(user, compare interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountChanges", reflect.TypeOf((*MockChangeDetector)(nil).GetAccountChanges), user, compare)
}

// GetCardChanges mocks base method.
func (m *MockChangeDetector) GetCardChanges(user client.User, compare changes.CardCompare) changes.CardChanges {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCardChanges", user, compare)
	ret0, _ := ret[0].(changes.CardChanges)
	return ret0
}

// GetCardChanges indicates an expected call of GetCardChanges.
func (mr *MockChangeDetectorMockRecorder) GetCardChanges(user, compare interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCardChanges", reflect.TypeOf((*MockChangeDetector)(nil).GetCardChanges), user, compare)
}

// GetNoteChanges mocks base method.
func (m *MockChangeDetector) GetNoteChanges(user client.User, compare changes.NoteCompare) changes.NoteChanges {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNoteChanges", user, compare)
	ret0, _ := ret[0].(changes.NoteChanges)
	return ret0
}

// GetNoteChanges indicates an expected call of GetNoteChanges.
func (mr *MockChangeDetectorMockRecorder) GetNoteChanges(user, compare interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNoteChanges", reflect.TypeOf((*MockChangeDetector)(nil).GetNoteChanges), user, compare)
}
